name: Practice github action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests  
        id: tests
        run: python -m pytest tests/test_api.py
        continue-on-error: false

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v4

      - name: Build docker image
        if: success()
        run: |
         docker build -t mywebserver:${{ github.sha }} .

      - name: Run Docker container
        if: success()
        run: |
          docker run -d -p 8080:80 --name webserver mywebserver:${{ github.sha }}

      - name: Test container is running
        if: success()
        run: |
          sleep 5
          docker ps | grep mywebserver     
