name: Practice github action
on: [push]
jobs:
  test-program:
    runs-on: ubuntu-latest
    steps:
      - run: apt update && git clone https://github.com/Amir-dev0/gha-lab-1.git
      - run: cd gha-lab-1
      - run: pip install -r requirements.txt
      - run: pytest test_program.py