name: Practice github action
on: [push]
jobs:
  test-program:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Installing requirements
        run: pip install -r requirements.txt

      - name: Testing  
        run: pytest test_program.py